services:
  api:
    container_name: nestjs
    image: nestjs-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      # 🧑‍💻 Target the dev stage
      # target: dev
    # Mount host directory to docker container to support watch mode
    volumes:
      - .:/app
      # This ensures that the NestJS container manages the node_modules folder
      # rather than synchronizes it with the host machine
      - /app/node_modules
    environment:
      # Prisma
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
      DIRECT_URL: "postgres://postgres:postgres@postgres:5432/postgres"
    ports:
      - 3000:3000
    networks:
      - nest
    depends_on:
      - postgres
    # command: npm run start:dev

  #  Database
  ## PostgreSQL
  postgres:
    container_name: postgres
    image: postgres:13.1-alpine
    restart: unless-stopped
    environment:
      # postgres
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - nest

  ## pgAdmin
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.30
    restart: unless-stopped
    environment:
      # pgadmin
      PGADMIN_DEFAULT_EMAIL: "admin@skinsight.fr"
      PGADMIN_DEFAULT_PASSWORD: "skinsight"
    ports:
      - 5050:80
    networks:
      - nest
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    command: /bin/sh -c "sleep 10; /entrypoint.sh"

  ## Metrics
  ## Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.22.0
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - nest
      - grafana
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  # Logging
  ## Loki
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana

  ## Promtail
  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - grafana

  ## Grafana
  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - "3333:3000"
    networks:
      - grafana
    environment:
      # grafana
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_USERS_ALLOW_SIGN_UP: false
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_BASIC_ENABLED: false
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_DISABLE_SIGNOUT_MENU: true
    volumes:
      - grafana:/var/lib/grafana
      # datasources in ./grafana/datasources.yaml
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      # dashboards in ./grafana/dashboards folder
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      # # config file in ./grafana/grafana.ini
      # - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - loki
      - promtail
      - prometheus

volumes:
  postgres:
  pgadmin:
  grafana:
  loki:
  promtail:


networks:
  nest:
  grafana:

