kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
      - match:
          priority: critical
        receiver: alert-emailer

    receivers:
    - name: alert-emailer
      email_configs:
      - to: '<>'
        from: '<>'
        smarthost: smtp.gmail.com:587
        auth_username: '<>'
        auth_identity: '<>'
        auth_password: '<>'
        send_resolved: true
