apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: api-dependencies-claim
  name: api-dependencies-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
