apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/backend-nest: "true"
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres.db:5432/postgres
            - name: DIRECT_URL
              value: postgres://postgres:postgres@postgres.db:5432/postgres
            - name: JWT_SECRET
              value: "mySecretKey"
            - name: ROUND_OF_HASHING
              value: "10"
          image: r0ht/skinsight:latest
          name: nestjs
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/src/app
              name: api-storage
            - mountPath: /usr/src/app/node_modules
              name: api-dependencies
      restartPolicy: Always
      volumes:
        - name: api-storage
          persistentVolumeClaim:
            claimName: api-storage-claim
        - name: api-dependencies
          persistentVolumeClaim:
            claimName: api-dependencies-claim
