apiVersion: 1
datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: http://postgres:5432
    database: postgres
    user: postgres
    password: postgres
    basicAuth: false
    editable: true
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      minTimeRange: 1m
    editable: true
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
