apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: grafana/promtail:latest
          args:
            - -config.file=/etc/promtail/promtail-config.yaml
          ports:
            - containerPort: 3101
          volumeMounts:
            - name: promtail-config-volume
              mountPath: /etc/promtail
      volumes:
        - name: promtail-config-volume
          configMap:
            defaultMode: 420
            name: promtail-config
