apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail-config.yaml: |-
    server:
      http_listen_port: 3101
    positions:
      filename: /run/promtail/positions.yaml
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
      - job_name: journal
        journal:
          max_age: 12h
          labels:
            job: systemd-journal
        relabel_configs:
          - source_labels: ['__journal__systemd_unit']
            target_label: 'unit'
          - source_labels: ['__journal__hostname']
            target_label: 'hostname'
          - action: replace
            replacement: 'journal'
            target_label: '__path__'
          - source_labels: ['__journal__identifier']
            target_label: 'identifier'
          - source_labels: ['__journal__message_id']
            target_label: 'message_id'
          - source_labels: ['__journal__boot_id']
            target_label: 'boot_id'
          - source_labels: ['__journal__cursor']
            target_label: 'cursor'
          - source_labels: ['__journal__source_monotonic_timestamp']
            target_label: 'source_monotonic_timestamp'
          - source_labels: ['__journal__source_realtime_timestamp']
            target_label: 'source_realtime_timestamp'
          - source_labels: ['__journal__source_timestamp']
            target_label: 'source_timestamp'
          - source_labels: ['__journal__systemd_owner_uid']
            target_label: 'systemd_owner_uid'
          - source_labels: ['__journal__systemd_slice']
            target_label: 'systemd_slice'
          - source_labels: ['__journal__systemd_unit']
            target_label: 'systemd_unit'
          - source_labels: ['__journal__systemd_user_slice']
            target_label: 'systemd_user_slice'
          - source_labels: ['__journal__systemd_user_unit']
            target_label: 'systemd_user_unit'
          - source_labels: ['__journal__systemd_cgroup']
            target_label: 'systemd_cgroup'
          - source_labels: ['__journal__systemd_service']
            target_label: 'systemd_service'
          - source_labels: ['__journal__systemd_invocation_id']
            target_label: 'systemd_invocation_id'
          - source_labels: ['__journal__systemd_machine_id']
            target_label: 'systemd_machine_id'
          - source_labels: ['__journal__systemd_boot_id']
            target_label: 'systemd_boot_id'
          - source_labels: ['__journal__systemd_hostname']
            target_label: 'systemd_hostname'
          - source_labels: ['__journal__systemd_transport']
            target_label: 'systemd_transport'
      - job_name: varlogs
        static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              __path__: /var/log/*log
