apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
spec:
  selector:
    app: loki
  ports:
    - name: loki
      protocol: TCP
      port: 3100
      targetPort: 3100
  type: ClusterIP
