apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      name: loki
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:latest
          ports:
            - name: loki
              containerPort: 3100
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
            requests:
              memory: 500M
              cpu: "500m"
          volumeMounts:
            - mountPath: /etc/loki
              name: loki-config
              readOnly: true
            - mountPath: /loki
              name: loki-storage
      volumes:
        - name: loki-config
          configMap:
            defaultMode: 420
            name: loki-config
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-volume-claim
