name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Send the image to the registry (github packages)
    - name: Login to GitHub Packages
      run: echo ${{ secrets.ORGANIZATION_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Build and push
      run: |
        REPO_NAME=$(echo ${{ github.repository }} | tr '[A-Z]' '[a-z]')
        docker buildx build --platform linux/amd64,linux/arm64 -t docker.pkg.github.com/$REPO_NAME/skinsight-api:latest --push .
