name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag skinsight/api:$(date +%s)
    # push to github package registry
    - name: Push to GitHub Package Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    # push to docker.pkg.github.com/skinsight/backend
    - run: docker push docker.pkg.github.com/skinsight/backend/skinsight/api:$(date +%s)
