apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: db
  labels:
    app: postgres
data:
  POSTGRES_DB: pg_db
  POSTGRES_USER: pg_user
  POSTGRES_PASSWORD: SecurePassword
